# SOME DESCRIPTIVE TITLE.
# Copyright (C) 1998-2024
# This file is distributed under the same license as the GDAL package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: GDAL master\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2024-06-26 10:24+0800\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: ../../../source/api/python/osgeo.ogr.rst:7
msgid "osgeo.ogr module"
msgstr ""

#: ../../../../../../.venv/lib/python3.8/site-packages/osgeo/ogr.py:docstring
#: of osgeo.ogr.ArrowArray:1 osgeo.ogr.ArrowArrayStream:1
#: osgeo.ogr.ArrowSchema:1 osgeo.ogr.ExceptionMgr:1
#: osgeo.ogr.GeomCoordinatePrecision:1 osgeo.ogr.GeomTransformer:1
#: osgeo.ogr.MajorObject:1 osgeo.ogr.PreparedGeometry:1
msgid "Bases: :py:class:`object`"
msgstr ""

#: ../../../../../../.venv/lib/python3.8/site-packages/osgeo/ogr.py:docstring
#: of osgeo.ogr.ArrowArray:1
msgid "Proxy of C++ ArrowArray class."
msgstr ""

#: ../../../../../../.venv/lib/python3.8/site-packages/osgeo/ogr.py:docstring
#: of osgeo.ogr.ArrowArrayStream:1
msgid "Proxy of C++ ArrowArrayStream class."
msgstr ""

#: ../../../../../../.venv/lib/python3.8/site-packages/osgeo/ogr.py:docstring
#: of osgeo.ogr.ArrowSchema:1
msgid "Proxy of C++ ArrowSchema class."
msgstr ""

#: ../../../../../../.venv/lib/python3.8/site-packages/osgeo/ogr.py:docstring
#: of osgeo.ogr.DontUseExceptions:1
msgid ""
"Disable exceptions in all GDAL related modules (osgeo.gdal, osgeo.ogr, osgeo."
"osr, osgeo.gnm). Note: prior to GDAL 3.7, this only affected the calling "
"module"
msgstr ""

#: ../../../../../../.venv/lib/python3.8/site-packages/osgeo/ogr.py:docstring
#: of osgeo.ogr.ExceptionMgr:1
msgid "Context manager to manage Python Exception state for GDAL/OGR/OSR/GNM."
msgstr ""

#: ../../../../../../.venv/lib/python3.8/site-packages/osgeo/ogr.py:docstring
#: of osgeo.ogr.ExceptionMgr:4
msgid ""
"Separate exception state is maintained for each module (gdal, ogr, etc), and "
"this class appears independently in all of them. This is built in top of "
"calls to the older UseExceptions()/DontUseExceptions() functions."
msgstr ""

#: ../../../../../../.venv/lib/python3.8/site-packages/osgeo/ogr.py:docstring
#: of osgeo.ogr.ExceptionMgr:9
msgid "Example::"
msgstr ""

#: ../../../../../../.venv/lib/python3.8/site-packages/osgeo/ogr.py:docstring
#: of osgeo.ogr.ExceptionMgr:11
msgid ""
">>> print(gdal.GetUseExceptions())\n"
"0\n"
">>> with gdal.ExceptionMgr():\n"
"...     # Exceptions are now in use\n"
"...     print(gdal.GetUseExceptions())\n"
"1\n"
">>>\n"
">>> # Exception state has now been restored\n"
">>> print(gdal.GetUseExceptions())\n"
"0"
msgstr ""

#: ../../../../../../.venv/lib/python3.8/site-packages/osgeo/ogr.py:docstring
#: of osgeo.ogr.GeomCoordinatePrecision:1
msgid "Proxy of C++ OGRGeomCoordinatePrecisionShadow class."
msgstr ""

#: ../../../../../../.venv/lib/python3.8/site-packages/osgeo/ogr.py:docstring
#: of osgeo.ogr.GeomTransformer:1
msgid "Proxy of C++ OGRGeomTransformerShadow class."
msgstr ""

#: ../../../../../../.venv/lib/python3.8/site-packages/osgeo/ogr.py:docstring
#: of osgeo.ogr.GetDriverByName:1
msgid ""
"Get a vector driver. Like :py:func:`gdal.GetDriverByName`, but only returns "
"drivers that handle vector data."
msgstr ""

#: ../../../../../../.venv/lib/python3.8/site-packages/osgeo/ogr.py:docstring
#: of osgeo.ogr.GetDriverByName:0 osgeo.ogr.Open:0 osgeo.ogr.OpenShared:0
msgid "Parameters"
msgstr ""

#: ../../../../../../.venv/lib/python3.8/site-packages/osgeo/ogr.py:docstring
#: of osgeo.ogr.GetDriverByName:4
msgid "name of the driver to fetch"
msgstr ""

#: ../../../../../../.venv/lib/python3.8/site-packages/osgeo/ogr.py:docstring
#: of osgeo.ogr.GetDriverByName:0 osgeo.ogr.Open:0 osgeo.ogr.OpenShared:0
msgid "Return type"
msgstr ""

#: ../../../../../../.venv/lib/python3.8/site-packages/osgeo/ogr.py:docstring
#: of osgeo.ogr.GetDriverByName:10 osgeo.ogr.Open:11
msgid "Examples"
msgstr ""

#: ../../../../../../.venv/lib/python3.8/site-packages/osgeo/ogr.py:docstring
#: of osgeo.ogr.MajorObject:1
msgid "Proxy of C++ GDALMajorObjectShadow class."
msgstr ""

#: ../../../../../../.venv/lib/python3.8/site-packages/osgeo/ogr.py:docstring
#: of osgeo.ogr.Open:1
msgid ""
"Open a vector file as a :py:class:`gdal.Dataset`. Equivalent to calling :py:"
"func:`gdal.OpenEx` with the :py:const:`gdal.OF_VECTOR` flag."
msgstr ""

#: ../../../../../../.venv/lib/python3.8/site-packages/osgeo/ogr.py:docstring
#: of osgeo.ogr.Open:5 osgeo.ogr.OpenShared:6
msgid "name of the file to open"
msgstr ""

#: ../../../../../../.venv/lib/python3.8/site-packages/osgeo/ogr.py:docstring
#: of osgeo.ogr.Open:8 osgeo.ogr.OpenShared:9
msgid "gdal.Dataset, or ``None`` on failure"
msgstr ""

#: ../../../../../../.venv/lib/python3.8/site-packages/osgeo/ogr.py:docstring
#: of osgeo.ogr.OpenShared:1
msgid ""
"Open a vector file as a :py:class:`gdal.Dataset`. If the file has already "
"been opened in the current thread, return a reference to the already-opened :"
"py:class:`gdal.Dataset`. Equivalent to calling :py:func:`gdal.OpenEx` with "
"the :py:const:`gdal.OF_VECTOR` and :py:const:`gdal.OF_SHARED` flags."
msgstr ""

#: ../../../../../../.venv/lib/python3.8/site-packages/osgeo/ogr.py:docstring
#: of osgeo.ogr.PreparedGeometry:1
msgid "Proxy of C++ OGRPreparedGeometryShadow class."
msgstr ""

#: ../../../../../../.venv/lib/python3.8/site-packages/osgeo/ogr.py:docstring
#: of osgeo.ogr.UseExceptions:1
msgid ""
"Enable exceptions in all GDAL related modules (osgeo.gdal, osgeo.ogr, osgeo."
"osr, osgeo.gnm). Note: prior to GDAL 3.7, this only affected the calling "
"module"
msgstr ""
